"""initial schema

Revision ID: cd032ddf86b0
Revises: 
Create Date: 2026-04-19 12:25:20.033967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd032ddf86b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('polymarket_condition_id', sa.String(length=128), nullable=False),
    sa.Column('polymarket_token_id', sa.String(length=128), nullable=False),
    sa.Column('event_slug', sa.String(length=255), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('price_threshold', sa.Integer(), nullable=False),
    sa.Column('scan_date', sa.Date(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('current_yes_price', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('current_no_price', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('selected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resolution', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markets_polymarket_condition_id'), 'markets', ['polymarket_condition_id'], unique=True)
    op.create_index(op.f('ix_markets_scan_date'), 'markets', ['scan_date'], unique=True)
    op.create_index(op.f('ix_markets_target_date'), 'markets', ['target_date'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_source'), 'system_logs', ['source'], unique=False)
    op.create_index(op.f('ix_system_logs_trace_id'), 'system_logs', ['trace_id'], unique=False)
    op.create_table('vault_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('total_assets', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('share_price', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('tvl', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('depositor_count', sa.Integer(), nullable=False),
    sa.Column('deployed_amount', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vault_snapshots_snapshot_at'), 'vault_snapshots', ['snapshot_at'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('predicted_probability', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('key_factors', sa.JSON(), nullable=False),
    sa.Column('risk_factors', sa.JSON(), nullable=False),
    sa.Column('technical_analysis', sa.Text(), nullable=False),
    sa.Column('sentiment_analysis', sa.Text(), nullable=False),
    sa.Column('news_impact', sa.Text(), nullable=False),
    sa.Column('onchain_analysis', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.String(length=16), nullable=False),
    sa.Column('market_probability', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('edge', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('prompt_version', sa.String(length=16), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('raw_request', sa.JSON(), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=False),
    sa.Column('data_snapshot', sa.JSON(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_market_id'), 'predictions', ['market_id'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=True),
    sa.Column('position_size', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('take_profit', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('kelly_fraction', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('edge', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('skip_reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_market_id'), 'strategies', ['market_id'], unique=False)
    op.create_index(op.f('ix_strategies_prediction_id'), 'strategies', ['prediction_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('polymarket_order_id', sa.String(length=128), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('amount', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('price', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('shares', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('fee', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('close_reason', sa.String(length=32), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('polymarket_order_id')
    )
    op.create_index(op.f('ix_trades_market_id'), 'trades', ['market_id'], unique=False)
    op.create_index(op.f('ix_trades_strategy_id'), 'trades', ['strategy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_strategy_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_market_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_strategies_prediction_id'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_market_id'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_predictions_market_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_vault_snapshots_snapshot_at'), table_name='vault_snapshots')
    op.drop_table('vault_snapshots')
    op.drop_index(op.f('ix_system_logs_trace_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_source'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_markets_target_date'), table_name='markets')
    op.drop_index(op.f('ix_markets_scan_date'), table_name='markets')
    op.drop_index(op.f('ix_markets_polymarket_condition_id'), table_name='markets')
    op.drop_table('markets')
    # ### end Alembic commands ###
